### ISSUE TITLE
im getting an import error

### ISSUE THREAD

**Issue by tinker1234** [kourgeorge/origin#5]
No module named 'tensorflow.contrib'
i dont know how to fix

**Comment by tinker1234** [comment]
C:\Users\win10\py\project-origin>py simulator.py
Traceback (most recent call last):
  File "simulator.py", line 6, in <module>
    from configsimulator import ConfigSimulator
  File "C:\Users\win10\py\project-origin\configsimulator.py", line 4, in <module>
    from creatures.humandqnbrain import HumanDQNBrain
  File "C:\Users\win10\py\project-origin\creatures\humandqnbrain.py", line 4, in <module>
    from brains.braindqntf import BrainDQN
  File "C:\Users\win10\py\project-origin\brains\braindqntf.py", line 6, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by pierrekour** [comment]
You have to downgrade your tensorflow version to <=1.14.
